# config/services.yaml

parameters:
  report_directory: "%kernel.project_dir%/var/reports"

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # Explicit service definition for TaskRepository
  App\Infrastructure\Persistence\Doctrine\TaskRepository:
    arguments:
      $registry: "@doctrine"

  App\Application\Service\Pomodoro\Strategy\ShortPomodoroStrategy:
    tags: ["pomodoro.strategy"]

  App\Application\Service\Pomodoro\Strategy\StandardPomodoroStrategy:
    tags: ["pomodoro.strategy"]

  App\Application\Service\Pomodoro\Strategy\LongPomodoroStrategy:
    tags: ["pomodoro.strategy"]

  App\Application\Service\PomodoroService:
    arguments:
      $defaultStrategy: '@App\Application\Service\Pomodoro\Strategy\StandardPomodoroStrategy'
      $requestStack: "@request_stack"

  # Controller service definition with injected services
  App\Application\Port\Http\Controller\PomodoroController:
    arguments:
      $pomodoroService: '@App\Application\Service\PomodoroService'
      $strategies:
        "short": '@App\Application\Service\Pomodoro\Strategy\ShortPomodoroStrategy'
        "standard": '@App\Application\Service\Pomodoro\Strategy\StandardPomodoroStrategy'
        "long": '@App\Application\Service\Pomodoro\Strategy\LongPomodoroStrategy'
    tags: ["controller.service_arguments"]

  App\Infrastructure\Notification\Observer\DiscordNotifier:
    arguments:
      $webhookUrl: "%env(DISCORD_WEBHOOK_URL)%"
      $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'

  App\Application\Service\NotificationService:
    arguments:
      $discordWebhookUrl: "%env(DISCORD_WEBHOOK_URL)%"

  App\Application\Service\TaskReportService:
    arguments:
      $reportDirectory: "%report_directory%"
